"""
Email sender.
Supports both SendGrid (recommended) and plain SMTP (e.g. Gmail).
Set EMAIL_PROVIDER in .env to "sendgrid" or "smtp".
"""

import os
import smtplib
import markdown
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


def render_html(briefing: dict, date_str: str) -> str:
    """Render the briefing dict into a styled HTML email."""
    sections_html = ""
    for domain_key, data in briefing.items():
        # Convert markdown bullets to HTML
        body_html = markdown.markdown(data["summary"])
        sections_html += f"""
        <div class="section">
          <h2>{data['emoji']} {data['name']}</h2>
          <div class="content">{body_html}</div>
        </div>
        """

    return f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      max-width: 640px;
      margin: 0 auto;
      padding: 24px;
      color: #1a1a1a;
      line-height: 1.6;
    }}
    .header {{
      border-bottom: 2px solid #f0f0f0;
      padding-bottom: 16px;
      margin-bottom: 24px;
    }}
    .header h1 {{ font-size: 22px; margin: 0 0 4px; }}
    .header p {{ color: #666; font-size: 14px; margin: 0; }}
    .section {{
      margin: 28px 0;
      padding-bottom: 20px;
      border-bottom: 1px solid #f0f0f0;
    }}
    .section:last-child {{ border-bottom: none; }}
    .section h2 {{
      font-size: 17px;
      margin: 0 0 10px;
      color: #1a1a1a;
    }}
    .content ul {{ padding-left: 20px; margin: 8px 0; }}
    .content li {{ margin: 8px 0; font-size: 14px; }}
    .footer {{
      margin-top: 32px;
      padding-top: 16px;
      border-top: 1px solid #f0f0f0;
      font-size: 12px;
      color: #888;
      text-align: center;
    }}
  </style>
</head>
<body>
  <div class="header">
    <h1>📰 Your Daily Briefing</h1>
    <p>{date_str}</p>
  </div>
  {sections_html}
  <div class="footer">
    Generated by your AI agent · Powered by Claude
  </div>
</body>
</html>"""


def send_via_sendgrid(html: str, subject: str):
    """Send via SendGrid API."""
    from sendgrid import SendGridAPIClient
    from sendgrid.helpers.mail import Mail

    message = Mail(
        from_email=os.environ["EMAIL_FROM"],
        to_emails=os.environ["EMAIL_TO"],
        subject=subject,
        html_content=html,
    )
    sg = SendGridAPIClient(os.environ["SENDGRID_API_KEY"])
    response = sg.send(message)
    if response.status_code >= 300:
        raise RuntimeError(f"SendGrid error: {response.status_code}")


def send_via_smtp(html: str, subject: str):
    """Send via SMTP (e.g. Gmail with an app password)."""
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = os.environ["EMAIL_FROM"]
    msg["To"] = os.environ["EMAIL_TO"]
    msg.attach(MIMEText(html, "html"))

    smtp_host = os.environ.get("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.environ.get("SMTP_PORT", "587"))

    with smtplib.SMTP(smtp_host, smtp_port) as server:
        server.starttls()
        server.login(os.environ["SMTP_USER"], os.environ["SMTP_PASSWORD"])
        server.send_message(msg)


def send_briefing_email(briefing: dict, date_str: str):
    """Format and send the daily briefing."""
    html = render_html(briefing, date_str)
    subject = f"📰 Daily Briefing — {date_str}"

    provider = os.environ.get("EMAIL_PROVIDER", "smtp").lower()
    if provider == "sendgrid":
        send_via_sendgrid(html, subject)
    else:
        send_via_smtp(html, subject)
